### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hal-wang** [hal-wang/Lavcode#1]
~~此 Issue 仅用于客户端反馈~~

反馈已改为自动创建新 Issue，此 Issue 将废弃

**Comment by hbrwang** [comment]
test .

**Comment by hbrwang** [comment]
这是一个测试》》》

# 哈哈哈

**Comment by hbrwang** [comment]
awefawe

**Comment by hbrwang** [comment]
test2

**Comment by hbrwang** [comment]
测试一下

**Comment by ghost** [comment]
不错

**Comment by hbrwang** [comment]
1. 测试
2. 试试

**Comment by hbrwang** [comment]
试试
嗯哼

**Comment by hbrwang** [comment]
测试

**Comment by hbrwang** [comment]
再测试一下

**Comment by hal-wang** [comment]
test

**Comment by hal-wang** [comment]
a

**Comment by hal-wang** [comment]
tttttt

**Comment by hal-wang** [comment]
都没有人反馈的？

**Comment by hal-wang** [comment]
ttt

**Comment by hal-wang** [comment]
ttt

**Comment by hal-wang** [comment]
test

**Comment by hal-wang** [comment]
aa

**Comment by hal-wang** [comment]
test

**Comment by Kohirus** [comment]
为什么只能在本地登录，登录Gitee或者Github都会提示网络错误？

**Comment by 5263s** [comment]
gitee会提示网络错误

**Comment by 5263s** [comment]
gitee会提示网络错误 可不可以弄一个密码隐藏显示的按钮

**Comment by hal-wang** [comment]
> 为什么只能在本地登录，登录Gitee或者Github都会提示网络错误？

可能是系统代理造成的，暂时没有找到其他原因

**Comment by hal-wang** [comment]
> gitee会提示网络错误 可不可以弄一个密码隐藏显示的按钮

可能是系统代理造成的，暂时没有找到其他原因

密码隐藏按钮在下个版本中会添加，感谢您的建议

**Comment by acrow** [comment]
突然登录不了了，我所有密码都保存在里面，这下被坑惨了！

**Comment by hal-wang** [comment]
> 突然登录不了了，我所有密码都保存在里面，这下被坑惨了！

请问是哪种存储方式登录不了？有没有什么提示？

**Comment by dadadaguyue** [comment]
#作者大大，存储是本地模式，突然打不开了，输入登录PIN码之后一直加载
- 数据存储在哪里，可以导出为数据库文件嘛
- 怎么恢复

**Comment by hal-wang** [comment]
> #作者大大，存储是本地模式，突然打不开了，输入登录PIN码之后一直加载
> 
> * 数据存储在哪里，可以导出为数据库文件嘛
> * 怎么恢复

导出的是加密后的文件，无法通过其他方式打开。

但本地文件没有加密，可以用数据库工具打开，文件是 sqlite3，路径为

```
C:\Users\<your name>\AppData\Local\Packages\524473F72DB2F.Lavcode_6m16nxjffxnpj\LocalState\localDb1.lc
```

可免费使用的数据库工具如 [Database.NET](https://fishcodelib.com/Database.htm)

**Comment by dadadaguyue** [comment]
是不是版本更新的bug，我8月底还存了几个密码，自动升到1.2一直没动后面刚开始用就这样了，可以回退嘛

**Comment by hal-wang** [comment]
> 是不是版本更新的bug，我8月底还存了几个密码，自动升到1.2一直没动后面刚开始用就这样了，可以回退嘛

有可能吧，前些天刚发版，这边再继续测试，如果找到问题会发新版

商店应用不支持回退，但你可以用以前的代码自行打包安装，但要注意备份本地文件

**Comment by hal-wang** [comment]
> 是不是版本更新的bug，我8月底还存了几个密码，自动升到1.2一直没动后面刚开始用就这样了，可以回退嘛

很抱歉，没有找到问题，也没能复现。能否提供一个出问题的密码文件？

```
C:\Users\<your name>\AppData\Local\Packages\524473F72DB2F.Lavcode_6m16nxjffxnpj\LocalState\localDb1.lc
```

发送邮件至 [support@hal.wang](mailto://support@hal.wang)

注意该文件中包含你的密码，请复制一份该文件并使用工具 [Database.NET](https://fishcodelib.com/Database.htm) 删除 `Password` 、`KeyValuePair` 表中的内容，就不用担心密码泄露了。


![image](https://user-images.githubusercontent.com/39717597/191937945-4d5e5f85-58a7-494d-ab3d-0e5ac75cc3ae.png)

其他遇到该问题的用户，看到这里也请发个文件帮助排查

**Comment by hal-wang** [comment]
> 是不是版本更新的bug，我8月底还存了几个密码，自动升到1.2一直没动后面刚开始用就这样了，可以回退嘛

版本 v1.2.4 已经修复这个问题

**Comment by hal-wang** [comment]
反馈功能已改为自动创建新 Issue，所以此 Issue 将关闭，不再用于反馈
